<?php
/**
 * Created by PhpStorm.
 * User: tik_squad
 * Date: 10/8/19
 * Time: 10:26 AM
 */

namespace DedeGunawan\TranskripAkademikUnsil\Utilities;


use Fpdf\Fpdf;

class CustomPdf extends Fpdf
{
    protected static $CustomPageSizes=[
        'f4' => array(609.448819,935.433071)
    ];

    function __construct(string $orientation = 'P', string $unit = 'mm', string $size = 'F4')
    {
        parent::__construct($orientation, $unit, $size);
    }

    function Header() {
        $mrg = 35;
        $pjg = 130;
        $this->Cell(182, 20, "", 0, 1);
        $this->Ln(2);
    }

    protected function _getpagesize($size)
    {
        $this->StdPageSizes = array_merge($this->StdPageSizes, self::getCustomPageSizes());
        return parent::_getpagesize($size); // TODO: Change the autogenerated stub
    }


    /**
     * @return array
     */
    public static function getCustomPageSizes(): array
    {
        return self::$CustomPageSizes;
    }
    /**
     * @return array | null
     */
    public static function getCustomPageSize($key)
    {
        return self::$CustomPageSizes[$key];
    }

    public static function setCustomPageSize($key, array $value)
    {
        self::$CustomPageSizes[$key] = $value;
    }

    public static function hasCustomPageSize($key)
    {
        return array_key_exists($key, self::$CustomPageSizes);
    }
}